### ISSUE TITLE
[dargon2]_TypeError dart_lib_loader.dart in DartLibLoader.getPath

### ISSUE THREAD

**Issue by hasimyerlikaya** [tmthecoder/dargon2#19] opened 2023-05-10 22:52 UTC
Hi,

I have an API that was developed with Dart and is running on the Google CloudRun Platform.
The API is working perfectly on my local machine (an iMac M1), but I'm getting an error when I publish.
The error is showing that there is a problem with Dragon2. I use it to encode passwords.

Is there any solution for this error?
Thank you.

**Configuration Details:**

` final result = await argon2.hashPasswordString(password, salt: saltBytes, memory: 128, iterations: 20, parallelism: 1);
`

**Error Details:**

<img width="1010" alt="image" src="https://github.com/tmthecoder/dargon2/assets/7986394/6a60555b-b14a-4c86-8357-c55d2a3c7e4e">

<img width="793" alt="image" src="https://github.com/tmthecoder/dargon2/assets/7986394/79390fdc-0fe1-4412-b3a5-770e431d736a">

**Comment by hasimyerlikaya** [comment] 2023-07-05 10:32
@tmthecoder Hi, can you check out this issue, please? I need to fix this error.

**Comment by tmthecoder** [comment] 2023-07-05 17:35
@hasimyerlikaya how is this running on Google CloudRun? Is it prepacked or running in a dart environment?

**Comment by hasimyerlikaya** [comment] 2023-07-05 17:40
> @hasimyerlikaya how is this running on Google CloudRun? Is it prepacked or running in a dart environment?

It runs inside a Docker container. Therefore, it is compiled as an exe. It runs on the local computer before compiling. But it doesn't work in docker package.

<img width="704" alt="image" src="https://github.com/tmthecoder/dargon2/assets/7986394/9e84a974-71a1-4a23-8866-62755d6f34c9">

**Comment by tmthecoder** [comment] 2023-07-05 17:45
Yeah that makes sense. It's odd to package ffi bundles with dart native compiled apps at the moment. I'm looking into fixes but unsure what my best path is for that at the moment

**Comment by hasimyerlikaya** [comment] 2023-07-05 17:47
Thank you very much. I hope you can fix that.

**Comment by tmthecoder** [comment] 2023-07-05 17:47
This is also a duplicate of #17, so I'll close this. Currently you can use the workaround described there to circumvent the crash running a packaged executable

**Closed as completed** 2023-07-05 17:47 UTC
