### ISSUE TITLE
dargon2_flutter_mobile not found

### ISSUE THREAD

**Issue by jogehl** [tmthecoder/dargon2#5] opened 2022-03-07 12:04 UTC
Hi, 
I have a problem while compiling to android. I always get the error dargon2_flutter_mobile not found. Please update settings.gradle.
Can anyone help me with this?

Greetings,

**Comment by tmthecoder** [comment] 2022-03-07 15:38
@jogehl hi, I can't help you out without more information. Could you send the stacktrace of the error you get? 

Additionally, it might be helpful to send over the pubspec declaration for dargon2.

**Comment by jogehl** [comment] 2022-03-07 15:48
Thanks a lot for your answer. The output is the following:

``` Launching lib/main.dart on moto g 7 in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :dargon2_flutter_mobile not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* Where:
Script '/home/joshuag/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 462

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot invoke method afterEvaluate() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 839ms
Exception: Gradle task assembleDebug failed with exit code 1
```

In the pubspec I use `  dargon2_flutter: ^3.1.0`

**Comment by tmthecoder** [comment] 2022-03-07 16:02
@jogehl thanks. Have you ran a pub get/update? It looks like your dependency hasn't downloaded.

**Comment by jogehl** [comment] 2022-03-07 16:10
I have run the pub get. But it seems that it has to be an error with my AndroidStudio. I have just run flutter run from console and it works without an error. So it is a problem with AndroidStudio and not with the package. But thanks a lot for your answer

**Comment by tmthecoder** [comment] 2022-03-07 16:16
No problem, I'll close this now then.

**Closed as completed by tmthecoder** 2022-03-07 16:16 UTC

**Comment by Crudar** [comment] 2022-06-28 12:45
Hi, after upgrading to Flutter 3.0.3 I have exactly the same issue. I tried to run it event from cmd via `flutter run`, but it didn't help. I have the same stacktrace and pubspec declaration as @jogehl.

**Comment by tmthecoder** [comment] 2022-06-28 13:10
@Crudar What's listed in your pubspec for the dependency?

**Comment by Crudar** [comment] 2022-06-28 13:43
@tmthecoder this one `dargon2_flutter: ^3.1.0`

**Comment by tmthecoder** [comment] 2022-06-28 13:57
Can you run `flutter pub get` and `flutter pub upgrade`? I can't reproduce the issue on my end so far

**Comment by Crudar** [comment] 2022-06-28 14:07
still the same issue, tried to run it on chrome and that works well

**Comment by tmthecoder** [comment] 2022-06-28 14:12
Does the same issue come up making a completely new flutter project on your end? Does iOS build?

**Comment by Crudar** [comment] 2022-06-28 14:45
I don't know what the issue was, but this helped me to fix it https://github.com/flutter/flutter/issues/57777#issuecomment-632609059**** anyway thank you for your time
